# This workflow uses ServiceNow custom actions that are certified by ServiceNow.

name: CI GitHub workflow

on: workflow_dispatch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  #   types: [opened, synchronize, reopened]

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean compile

  test:
    name: 'Test'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Run Tests with Maven
      run: mvn -B test --file pom.xml 
    - name: ServiceNow DevOps Unit Test Results
      uses: ServiceNow/servicenow-devops-test-report@v3.0.0
      with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Test'
          xml-report-filename: target/surefire-reports/testng-results.xml
          
  registerartifact:
    name: Register Artifact
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Extract Version
      run: |
          version=$(sed -n 's,.*<version>\(.*\)</version>.*,\1,p' pom.xml | head -1)
          echo " Version extrated from pom.xml: $version"
          echo "pomversion=$(echo $version)" >> "$GITHUB_ENV"
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
          echo "" > $(git rev-parse --short "$GITHUB_SHA")
          
    - name: ServiceNow Register Artifact
      uses: ServiceNow/servicenow-devops-register-artifact@v2.0.0
      with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: 'Register Artifact'
          artifacts: '[{"name": "repo1-artifact1-${{ env.branch }}-${{ env.sha_short }}.jar","version": "${{ env.pomversion}}","semanticVersion": "${{ env.pomversion}}","repositoryName": "${{ github.repository }}"}]'
   
    - name: Push to Build Registry
      uses: dmnemec/copy_file_to_another_repo_action@main
      env: 
        API_TOKEN_GITHUB: ${{ secrets.Build_REPO_PERSONAL_ACCESS_TOKEN }}   
      with:
        # GitHub Action output files
        source_file: '${{ env.sha_short }}'
        user_name: 'ArunKumarReddy407'
        destination_repo: 'ArunKumarReddy407/buildmetadata'
        destination_folder: 'release/comp2/'
        #user-email: <your email>
        # It defaults to `main`
        #target-branch: "main"
        commit_message: 'Push artifact1 to Build registry repo'
